### PR TITLE
Fix Offset in Brush Events for Scatter and Density Plots

### LINKED ISSUE #91: 2d Select on "DENSITY_2D" and "scatter" doesn't work right on Firefox
For example, 
image

Click and drag is usually not as expected, and instead outside of the area entirely!

### PR DESCRIPTION
**Pull request by MohamedNasser8**
I added padding in the x axis and y axis so all points are clear and can axis all of them by filter.

### CODE REVIEW

**Comment by birm** [comment]
This doesn't seem to fix the bug in firefox with the brush events for me.

**Review by birm — APPROVED** [review]
Thanks for clarifying; this does fix the offset issue in edge and chrome, so I'm happy to approve. Still very confused on the firefox bug though!

**Comment by MohamedNasser8** [comment]
I am downloading firefox now to see it

**Comment by birm** [comment]
I'll merge this for now. If you figure out the firefox-related brush events bug, please open another PR. Thanks for the contribution!

**Pull request merged**
