### PR TITLE
fixes #91

### LINKED ISSUE #91: 2d Select on "DENSITY_2D" and "scatter" doesn't work right on Firefox
For example, 
image

Click and drag is usually not as expected, and instead outside of the area entirely!

### PR DESCRIPTION
**Pull request by MohamedNasser8**
Update 2d selection on fire fox for scattering plot

### CODE REVIEW

**Comment by birm** [comment]
Amazing work! Do you think you can do it for the "DENSITY_2D" chart too? If you don't want to, I'll just merge this as is.

**Comment by MohamedNasser8** [comment]
Yes, I will complete it for density chart also.

**Review by birm — APPROVED** [review]
Fantastic work, and thank you!

**Comment by MohamedNasser8** [comment]
You'r welcome, There are some bugs with the density plot i will try to solve them.

**Pull request merged**
